#ifndef __MSG__
#define __MSG__

enum tag_login{REGISTERED=0,LOGIN,UPLOAD_F,UPLOAD_S,DOWNLOAD,ADDFRIEND,SHAREDTOFRIEND,SNOPSHOT};

enum ser_ret{REGISTERED_RET=0,LOGIN_SUCCESS,FRIEND_LIST,FILE_LIST,ERROR_PASSWD,RESUME};

#endif